# Generated by Django 4.2.3 on 2023-07-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootisfi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genres',
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(to='bootisfi.genre'),
        ),
    ]
