# Generated by Django 4.2.3 on 2023-07-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootisfi', '0004_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
    ]
