# Generated by Django 4.2.3 on 2023-07-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootisfi', '0006_alter_playlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='playlist_images/background_palylist.jpg', upload_to='playlist_images/'),
        ),
    ]
